### PR TITLE
#112 add sync module to account SPA

### PR DESCRIPTION
**Pull request by asmaNode**
UPDATED DEMO  :

https://user-images.githubusercontent.com/43316837/159470358-e1803625-2837-49f9-9809-c575953cffd5.mp4

TODO list:

- [x] Move All frontend module of project linagora.esn.sync under esn-frontend-account

- [x] Update logic to  compile markdown in html pages on frontend side  

- [x]  handle the problem of ejs variables in markdowns by static data
- [x] handle image path error on markdowns pages

### CODE REVIEW

**Comment by chamerling** [comment]
From what I remember, the HTML pages where compiled on the server from markdown (or similar). How do you manage this now? I will suggest to do eveything at compile time (and inject data from server at render time)

**Comment by asmaNode** [comment]
for the moment I have not yet thought I started by integrating the missing module, we have to think how we should deal with this

**Comment by asmaNode** [comment]
@chamerling i suggest to convert all the md file to html (pug files under each component) , i think there is no need to do this in compile time , WDYT? 
@renaudboyer

**Comment by chamerling** [comment]
Writing documentation in PUG is boring, having it in Markdown will be easier...

**Review by alagane — DISMISSED** [review]

**Review by alagane — DISMISSED** [review]

**Comment by alagane** [comment]
Superseded by #114

**Pull request closed without merging**
